/** Declaration file generated by dts-gen */

export function extract(cwd: any, opts?: any): any;

export function pack(cwd: any, opts: any): any;

export namespace extract {
    const prototype: {
    };

}

export namespace pack {
    const prototype: {
    };

}

