name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Enable Docker IPv6
        run: |
          echo '{ "ipv6": true }' | sudo tee -a /etc/docker/daemon.json
          sudo systemctl reload docker

      - name: Install required OS packages
        run: sudo apt-get install -y build-essential moreutils zstd

      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Pull required docker images
        run: docker pull eu.gcr.io/moocfi-public/tmc-sandbox-tmc-langs-rust

      - name: Run tests
        run: pnpm test
